Q1. WHO IS THE SENIOR MOST EMPLOYEE BASED ON JOB TITLE?

SELECT * FROM EMPLOYEE
SELECT LAST_NAME, FIRST_NAME FROM EMPLOYEE WHERE REPORTS_TO IS NULL  

Q2.WHICH COUNTRY HAVE MOST INVOICES?

SELECT * FROM INVOICE

SELECT BILLING_COUNTRY, COUNT(TOTAL) AS SUM
FROM INVOICE GROUP BY BILLING_COUNTRY
ORDER BY SUM DESC

Q3. WHAT ARE  THE TOP THREE VALUES OF TOTAL INVOICE?
 
 SELECT * FROM INVOICE
 SELECT BILLING_COUNTRY ,TOTAL FROM INVOICE
 ORDER BY TOTAL DESC LIMIT 3
 
 Q4. WRITE A QUERY THAT RETURNS ONE CITY THAT HAS HIGHEST SUM OF INVOICES TOTALS.
 RETURN BOTH THE CITY NAME AND SUM OF ALL INVOCES TOTALS?
 
 SELECT * FROM INVOICE
 SELECT BILLING_CITY, SUM(TOTAL) AS SUM
 FROM INVOICE GROUP BY BILLING_CITY
 ORDER BY SUM DESC
 
 Q5. PERSON WHO HAS SPENT MOST MONEY?
 
 SELECT * FROM CUSTOMER
  SELECT * FROM INVOICE
  
  SELECT CUSTOMER.CUSTOMER_ID, CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME, SUM(INVOICE.TOTAL) AS BEST
  FROM CUSTOMER
  JOIN INVOICE ON CUSTOMER.CUSTOMER_ID= INVOICE.CUSTOMER_ID
  GROUP BY CUSTOMER.CUSTOMER_ID
  ORDER BY BEST DESC  LIMIT 1

SELECT ARTIST.ARTIST_ID, ARTIST.NAME, COUNT(ARTIST.ARTIST_ID) AS NUMBER_SONGS FROM TRACK
JOIN ALBUM ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
JOIN ARTIST ON ARTIST.ARTIST_ID= ALBUM.ARTIST_ID
JOIN GENRE ON GENRE.GENRE_ID= TRACK.GENRE_ID
WHERE GENRE.NAME = 'ROCK'
GROUP BY ARTIST.ARTIST_ID
ORDER BY NUMBER_SONGS DESC
LIMIT 10;


SELECT NAME, MILLISECONDS AS LENGHT FROM TRACK
WHERE MILLISECONDS >(SELECT AVG(MILLISECONDS) AS LENGHT
FROM TRACK)







